/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package newpackage;

/**
 *
 * @author mrato
 */
import java.awt.Color;
import java.sql.*;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableModel;
public class ManageBooks_1 extends javax.swing.JFrame {

    /**
     * Creates new form ManageBooks
     */
    Color color = new Color(0,0,0);
    Color clicked = new Color(51,51,51);
    DefaultTableModel student;
    public ManageBooks_1() throws SQLException {
        initComponents();
        saveTableData();
    }
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        studentID = new javax.swing.JTextField();
        jLabel14 = new javax.swing.JLabel();
        name = new javax.swing.JTextField();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        rSMaterialButtonCircle2 = new rojerusan.RSMaterialButtonCircle();
        rSMaterialButtonCircle3 = new rojerusan.RSMaterialButtonCircle();
        rSMaterialButtonCircle4 = new rojerusan.RSMaterialButtonCircle();
        field2 = new javax.swing.JComboBox<>();
        field1 = new javax.swing.JComboBox<>();
        jPanel3 = new javax.swing.JPanel();
        jPanel4 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        studentTable = new javax.swing.JTable();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(153, 204, 255));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel2.setBackground(new java.awt.Color(255, 51, 51));

        jLabel1.setFont(new java.awt.Font("Segoe UI Black", 0, 17)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/newpackage/AddNewBookIcons/icons8_Rewind_48px.png"))); // NOI18N
        jLabel1.setText("BACK");
        jLabel1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel1MouseClicked(evt);
            }
        });
        jPanel2.add(jLabel1);

        jPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 140, 50));

        jLabel13.setFont(new java.awt.Font("Segoe UI Historic", 1, 12)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(255, 255, 255));
        jLabel13.setText("INDEX NUMBER");
        jPanel1.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 140, 229, 29));

        studentID.setBackground(new java.awt.Color(51, 51, 255));
        studentID.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 2, 0, new java.awt.Color(255, 255, 255)));
        studentID.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                studentIDFocusLost(evt);
            }
        });
        studentID.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                studentIDActionPerformed(evt);
            }
        });
        jPanel1.add(studentID, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 190, 270, 30));

        jLabel14.setFont(new java.awt.Font("Segoe UI Historic", 1, 12)); // NOI18N
        jLabel14.setForeground(new java.awt.Color(255, 255, 255));
        jLabel14.setText("Student Name");
        jPanel1.add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 240, 229, 29));

        name.setBackground(new java.awt.Color(51, 51, 255));
        name.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 2, 0, new java.awt.Color(255, 255, 255)));
        name.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nameActionPerformed(evt);
            }
        });
        jPanel1.add(name, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 280, 270, 30));

        jLabel15.setFont(new java.awt.Font("Segoe UI Historic", 1, 12)); // NOI18N
        jLabel15.setForeground(new java.awt.Color(255, 255, 255));
        jLabel15.setText("SELECT LEVEL OF EDUCATION");
        jPanel1.add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 320, 229, 29));

        jLabel16.setFont(new java.awt.Font("Segoe UI Historic", 1, 12)); // NOI18N
        jLabel16.setForeground(new java.awt.Color(255, 255, 255));
        jLabel16.setText("PROGRAMME");
        jPanel1.add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 400, 229, 29));

        rSMaterialButtonCircle2.setBackground(new java.awt.Color(255, 51, 51));
        rSMaterialButtonCircle2.setText("Delete");
        rSMaterialButtonCircle2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                rSMaterialButtonCircle2MouseClicked(evt);
            }
        });
        rSMaterialButtonCircle2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rSMaterialButtonCircle2ActionPerformed(evt);
            }
        });
        jPanel1.add(rSMaterialButtonCircle2, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 540, 90, 60));

        rSMaterialButtonCircle3.setBackground(new java.awt.Color(255, 51, 51));
        rSMaterialButtonCircle3.setText("ADD");
        rSMaterialButtonCircle3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                rSMaterialButtonCircle3MouseClicked(evt);
            }
        });
        rSMaterialButtonCircle3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rSMaterialButtonCircle3ActionPerformed(evt);
            }
        });
        jPanel1.add(rSMaterialButtonCircle3, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 540, 90, 60));

        rSMaterialButtonCircle4.setBackground(new java.awt.Color(255, 51, 51));
        rSMaterialButtonCircle4.setText("UpDate");
        rSMaterialButtonCircle4.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                rSMaterialButtonCircle4MouseClicked(evt);
            }
        });
        rSMaterialButtonCircle4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rSMaterialButtonCircle4ActionPerformed(evt);
            }
        });
        jPanel1.add(rSMaterialButtonCircle4, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 540, 90, 60));

        field2.setBackground(new java.awt.Color(51, 51, 255));
        field2.setFont(new java.awt.Font("Arial Narrow", 1, 14)); // NOI18N
        field2.setForeground(new java.awt.Color(255, 255, 255));
        field2.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "MECHANICAL ENGINEERING", "CIVIL ENGINEERING", "PETROLEUM ENGINEERING", "BCOM FINANCE", "BCOM MARKETING", "ELECTRICAL ENGINEERING", "LAW", "MEDICINE", "OPTOMETRY", "COMPUTER SCIENCE", "THEATRE ART AND FILMING", "GEOGRAPHY AND REGIONAL PLANNING", "BIOMEDICAL SCIENCE", "FISHERIES AND ACQUATIC" }));
        jPanel1.add(field2, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 440, 270, 30));

        field1.setBackground(new java.awt.Color(51, 51, 255));
        field1.setFont(new java.awt.Font("Arial Narrow", 1, 14)); // NOI18N
        field1.setForeground(new java.awt.Color(255, 255, 255));
        field1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "BSC", "MSC", "PHD" }));
        jPanel1.add(field1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 350, 270, 30));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 350, 820));
        getContentPane().add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 90, 40));

        jPanel4.setBackground(new java.awt.Color(255, 255, 255));
        jPanel4.setForeground(new java.awt.Color(255, 255, 255));
        jPanel4.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        studentTable.setBackground(new java.awt.Color(204, 204, 255));
        studentTable.setFont(new java.awt.Font("Calibri", 1, 14)); // NOI18N
        studentTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "STUDENT ID", "STUDENT NAME", "LEVEL", "PROGRAMME"
            }
        ));
        studentTable.setRowHeight(30);
        studentTable.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                studentTableMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(studentTable);

        jPanel4.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 220, 820, 410));

        jLabel2.setFont(new java.awt.Font("Segoe UI", 0, 30)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 51, 51));
        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/newpackage/AddNewBookIcons/icons8_Student_Male_100px.png"))); // NOI18N
        jLabel2.setText("Manage Student");
        jPanel4.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 40, 330, -1));

        getContentPane().add(jPanel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 0, 1180, 820));

        setSize(new java.awt.Dimension(1740, 832));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jLabel1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel1MouseClicked
        HomePage Home = new HomePage();
        Home.setVisible(true);
        dispose();
        
    }//GEN-LAST:event_jLabel1MouseClicked

    private void saveTableData() throws SQLException{
        Connection con = DbConnection.getConnection();
        Statement statement = con.createStatement();
       ResultSet resultSet = statement.executeQuery("SELECT * FROM studenttable");
       while(resultSet.next()){
           String indexNumeber = resultSet.getString("Student_Id");
           String studentName = resultSet.getString("Student_Name");
           String field = resultSet.getString("Programme");
           String programme = resultSet.getString("datafield");
           Object [] details = {indexNumeber, studentName, field, programme};
           student = (DefaultTableModel) studentTable.getModel();
           student.addRow(details);
           
       }
       
        
    }
    public void clearTable(){
        DefaultTableModel model = (DefaultTableModel) studentTable.getModel();
        model.setRowCount(0);
        
    }
    private boolean upDateBook() throws SQLException{
        boolean isUpdated = false;
        String indexNumber  = studentID.getText();
        String names =  name.getText();
        String field = field1.getSelectedItem().toString();
        String fields = field2.getSelectedItem().toString() ;
        Connection con = DbConnection.getConnection();
        String Statements = "UPDATE studenttable SET Student_Name = ?, Programme = ?, datafield = ? WHERE Student_Id = ? ";
        PreparedStatement statement = con.prepareStatement(Statements);
       
        statement.setString(1, names);
        statement.setString(2, field);
        statement.setString(3, fields);
         statement.setString(4, indexNumber);
       int inserted = statement.executeUpdate();
       if(inserted > 0){
           isUpdated = true;
       }else{
           isUpdated = false;
       }
       return isUpdated;
                
        
    }
    public boolean deleteBook() throws SQLException{
        boolean isdeleted = false;
        String indexNumber = studentID.getText();
        Connection connection = DbConnection.getConnection();
        String Query = "DELETE FROM studenttable WHERE book_id = ?";
        PreparedStatement statement =  connection.prepareStatement(Query);
        statement.setString(1, indexNumber);
        int result = statement.executeUpdate();
        if(result > 0){
            isdeleted = true;
        }else{
            isdeleted = false;
        }
        return isdeleted;
        
    }
    private void studentIDFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_studentIDFocusLost
       
    }//GEN-LAST:event_studentIDFocusLost

    private void studentIDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_studentIDActionPerformed
        // TODO add your handling code here:
        
    }//GEN-LAST:event_studentIDActionPerformed

    private void nameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_nameActionPerformed

    private void rSMaterialButtonCircle2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rSMaterialButtonCircle2ActionPerformed
        // TODO add your handling code here:
      

    }//GEN-LAST:event_rSMaterialButtonCircle2ActionPerformed

    private void rSMaterialButtonCircle3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rSMaterialButtonCircle3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_rSMaterialButtonCircle3ActionPerformed

    private void rSMaterialButtonCircle4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rSMaterialButtonCircle4ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_rSMaterialButtonCircle4ActionPerformed

    private void studentTableMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_studentTableMouseClicked
        int getSelectedRow =  studentTable.getSelectedRow();
        TableModel tableModel = studentTable.getModel();
        studentID.setText(tableModel.getValueAt(getSelectedRow,0).toString());
        name.setText(tableModel.getValueAt(getSelectedRow, 1).toString());
        field1.setSelectedItem(tableModel.getValueAt(getSelectedRow, 2));
        field2.setSelectedItem(tableModel.getValueAt(getSelectedRow, 3));
    }//GEN-LAST:event_studentTableMouseClicked

    private void rSMaterialButtonCircle3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_rSMaterialButtonCircle3MouseClicked
        try {
            // TODO add your handling code here:
            if(addStudent()){
                JOptionPane.showMessageDialog(this, "Book Added Succesfully");
                clearTable();
                saveTableData();
                
            }else{
                JOptionPane.showMessageDialog(this, "Could'nt not added the book to the database");
            }
        } catch (SQLException ex) {
            Logger.getLogger(ManageBooks.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_rSMaterialButtonCircle3MouseClicked

    private void rSMaterialButtonCircle4MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_rSMaterialButtonCircle4MouseClicked
        try {
            if(upDateBook()){
                JOptionPane.showMessageDialog(this, "Book has been successfully added");
                
            }else{
                JOptionPane.showMessageDialog(this, "Updation failed");
            }
        } catch (SQLException ex) {
            Logger.getLogger(ManageBooks.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_rSMaterialButtonCircle4MouseClicked

    private void rSMaterialButtonCircle2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_rSMaterialButtonCircle2MouseClicked
        try {
            if(deleteBook()){
                JOptionPane.showMessageDialog(this, "Book deleted successfully");
                
            }else{
                JOptionPane.showMessageDialog(this, "Could not delete book try again");
            }
        } catch (SQLException ex) {
            Logger.getLogger(ManageBooks.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_rSMaterialButtonCircle2MouseClicked

    private Boolean addStudent() throws SQLException{
        boolean isAdded = false;
        String studentId = studentID.getText();
        String studentName = name.getText();
        String checkField = field1.getSelectedItem().toString();
        String checkField2 = field2.getSelectedItem().toString();
        
        
        Connection connection  = DbConnection.getConnection();
        String query = "INSERT INTO studenttable values (?,?,?,?)";
        PreparedStatement statement = connection.prepareStatement(query);
        statement.setString(1, studentId);
        statement.setString(2, studentName);
        statement.setString(3, checkField);
        statement.setString(4, checkField2);
        
        
        int inserted = statement.executeUpdate();
        isAdded = inserted > 0;
        return isAdded;
        
        
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ManageBooks.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ManageBooks.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ManageBooks.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ManageBooks.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                try {
                    new ManageBooks().setVisible(true);
                } catch (SQLException ex) {
                    Logger.getLogger(ManageBooks.class.getName()).log(Level.SEVERE, null, ex);
                }
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> field1;
    private javax.swing.JComboBox<String> field2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField name;
    private rojerusan.RSMaterialButtonCircle rSMaterialButtonCircle2;
    private rojerusan.RSMaterialButtonCircle rSMaterialButtonCircle3;
    private rojerusan.RSMaterialButtonCircle rSMaterialButtonCircle4;
    private javax.swing.JTextField studentID;
    private javax.swing.JTable studentTable;
    // End of variables declaration//GEN-END:variables
}
